import { notFound } from "next/navigation";
import Link from "next/link";
import ReactMarkdown from "react-markdown";
import Nav from "@/components/Nav";
import episodes from "@/data/episodes.json";
interface Props { params: Promise<{ number: string }> }
export async function generateStaticParams() { return episodes.map(ep=>({number:String(ep.number)})); }
export async function generateMetadata({params}:Props){const {number}=await params;const ep=episodes.find(e=>e.number===Number(number));return ep?{title:`${ep.title} | 운명의 이룸`,description:ep.preview}:{};}
function cleanContent(content:string){return content.replace(/^# 운명의 이룸\s*\n+/,"").replace(/^## 제\d+화[^\n]*\n+/,"").trim();}
export default async function EpisodePage({params}:Props){const {number}=await params;const num=Number(number);const ep=episodes.find(e=>e.number===num);if(!ep)notFound();const prev=episodes.find(e=>e.number===num-1);const next=episodes.find(e=>e.number===num+1);return <><Nav/><main className="reader-page"><div className="reader-bar shell"><Link href="/episodes">← 목차</Link><span>운명의 이룸 / {String(num).padStart(3,"0")}</span><span>{episodes.length}화 중 {num}화</span></div><article className="reader-article"><header className="reader-header"><p className="eyebrow">CHAPTER {String(num).padStart(3,"0")}</p><h1>{ep.title}</h1><time>{ep.date}</time></header><div className="novel-body"><ReactMarkdown>{cleanContent(ep.content)}</ReactMarkdown></div>{ep.authorNote&&<aside className="author-note"><span>작가의 한마디</span><p>{ep.authorNote}</p><small>— 지혜</small></aside>}<nav className="reader-nav" aria-label="회차 이동">{prev?<Link href={`/episode/${prev.number}`}><small>← 이전 화</small><strong>{prev.title}</strong></Link>:<span/>}{next?<Link href={`/episode/${next.number}`}><small>다음 화 →</small><strong>{next.title}</strong></Link>:<span className="next-pending"><small>다음 화</small><strong>준비 중</strong></span>}</nav><Link href="/episodes" className="back-to-list">전체 목차로 돌아가기 ↗</Link></article></main><footer className="site-footer"><div className="shell footer-inner"><span>운명의 이룸</span><span>기록은 계속된다.</span></div></footer></>}
